### ISSUE TITLE
Body is not being tracked

### ISSUE THREAD

**Issue by vishwanathbijalwan** [violetasdev/bodytrackingdepth_course#33]
Hello Violetasdev, 

Thank you for sharing your code, it is highly commendable. 

I am facing some problem. If you could shed some light, it is highly appreciable. 

I am running this code, and I am not able to track the body. Here is the screenshot I am getting after running this code. 

 
![pic1](https://user-images.githubusercontent.com/64492703/208625020-bafc498b-1686-4d50-abef-aac0c014ea1f.png)
![pic 2](https://user-images.githubusercontent.com/64492703/208625140-da3c50d6-f432-416b-8441-fed008ae48b2.png)

Could you please tell me what I should do for body tracking. Thank you.

**Comment by violetasdev** [comment]
Hi @vishwanathbijalwan!

Here are a few things to try/check:

- I noticed in your first image that the camera was updating the skeleton libraries. Did the process finish properly? 
- Stand farther away from the camera and show your entire body. Additionally, avoid a background in which the body will be merging with, i.e. black t-shirt with a black monitor, at least for now, for testing; that is a good approach as this camera works by combining two RGB perspectives to asses the depth. 
- Another option is to use the original code from Stereolabs, which doesn't save the skeleton data to an external file! You can find the code here: [Stereolabs Python Code](https://github.com/stereolabs/zed-examples/tree/master/body%20tracking/python)

I am glad to know the code is helping more and more people! 💯 

Keep me posted,

Violeta

**Comment by vishwanathbijalwan** [comment]
Hello Violetasdev, Thank you for the help. actually i was trying human body tracking and want to use synchronized multi camera(in my case 02 camera) simultaneously.  i am facing some problems. but anyways thank you..
